server:
  port: 8081

spring:
  application:
    name: decoy-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/honeymesh?currentSchema=decoy}
    username: ${SPRING_DATASOURCE_USERNAME:honeymesh}
    password: ${SPRING_DATASOURCE_PASSWORD:honeymesh_dev_pw}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:honeymesh}
    password: ${SPRING_RABBITMQ_PASSWORD:honeymesh_dev_pw}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

jwt:
  secret: ${JWT_SECRET:honeymesh-dev-jwt-signing-secret-change-before-any-real-deployment-2026}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
